---
# cassie_joy_env Environment Parameters
env_params:
    x_lims: [-1, 6]
    y_lims: [-3, 6]
    z_lims: [0.5, 1.3]
    rate_hz: 4
    goal_state: [1, 1]
    visualize: True

    # 0 for flat, 1 for gaps, 2 for large obstacles, 3 for stairs
    terrain_class: 2
    num_features: 3

    # 0 for zeroth order (-distance to goal), 1 for progress in last step, etc.
    # 2 for a sparse reward with dense penalty
    reward_fn: 1
    use_acc_penalty: True

# RL Parameters:
ppo_params:
    num_episodes: 30000
    batch_size: 16
    n_steps: 128
    verbose: 2
