---
# cassie_singleobst_env Parameters
env_params:
    x_lims: [-4, 4]
    y_lims: [-4, 4]
    z_lims: [0.5, 1.3]

    rate_hz: 5
    goal_state: [3, 0]
    visualize: True
    blind: True


# RL Parameters:
rl_params:
    num_steps: 150000
    learning_starts: 200
    batch_size: 32
    verbose: 2
    buffer_size: 20000
    learning_rate: 3e-4
